// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package comet

import (
	"github.com/go-kratos/kratos/v2"
	"gnettest/internal/comet/conf"
	"gnettest/internal/comet/server/socket"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(config *conf.Config) (*kratos.App, error) {
	server := socket.NewServer(config)
	app := newApp(server)
	return app, nil
}
